import React from "react";

function Stat({ label, value, accent }) {
  return (
    <div className="bg-white/[0.03] border border-white/5 rounded-2xl p-6">
      <p className="text-[10px] font-bold uppercase tracking-widest text-slate-500 mb-2">{label}</p>
      <p className={`text-3xl font-black ${accent || "text-white"}`}>{value ?? "—"}</p>
    </div>
  );
}

export default function Overview({ stats, counts, statsError }) {
  return (
    <div className="space-y-6">
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <Stat label="Pending Blogs" value={counts.blog} accent="text-amber-400" />
        <Stat label="Pending Emails" value={counts.email} accent="text-amber-400" />
        <Stat label="Pending WhatsApp" value={counts.whatsapp} accent="text-amber-400" />
        <Stat label="Total Blogs" value={stats?.totalBlogs} />
      </div>

      <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
        <Stat label="Autonomous Runs" value={stats?.totalRuns} />
        <Stat label="Successful Runs" value={stats?.successfulRuns} accent="text-emerald-400" />
        <Stat label="Failed Runs" value={stats?.failedRuns} accent="text-rose-400" />
      </div>

      {statsError && (
        <div className="bg-amber-500/10 border border-amber-500/30 text-amber-300 text-sm rounded-xl px-5 py-4">
          Could not load pipeline stats ({statsError}). The approval queues below still work independently.
        </div>
      )}

      <div className="bg-white/[0.03] border border-white/5 rounded-2xl p-6 text-sm text-slate-400 leading-relaxed">
        Every blog, email, and WhatsApp message generated by the agents lands here first with a{" "}
        <span className="text-amber-300 font-semibold">pending</span> status. Nothing is sent or
        published automatically — an admin must <span className="text-sky-300 font-semibold">approve</span>{" "}
        it, and then hit <span className="text-emerald-300 font-semibold">Publish / Send Now</span> to
        release it. Rejected items are kept for reference and can be moved back to pending.
      </div>
    </div>
  );
}
